services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: backend_server
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "5000:5000"
 
  client:
    build: ./client
    container_name: frontend_client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  pgdata:
